PYTHON NUMPY

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [7]:
import numpy as np
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3]])
c = np.array([[[3,4,5],[3,4,5],[4,5,6]],[[3,4,5],[3,4,5],[4,5,6]]])
print(a)

[1 2 3]


In [8]:
print(b)

[[1 2 3]
 [1 2 3]]


In [10]:
print(c)

[[[3 4 5]
  [3 4 5]
  [4 5 6]]

 [[3 4 5]
  [3 4 5]
  [4 5 6]]]


INITIAL PLACEHOLDERS

In [11]:
# create an array of zeros

In [12]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
# create an array of ones

In [13]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
# create an array of evenly space values:

In [17]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [18]:
# create an constant array: create a 1D array

In [21]:
e = np.full((2),7)
print(e)
print("dim",e.ndim)

[7 7]
dim 1


In [20]:
# create a 2D array

In [23]:
e = np.full((4,5,7),6)
print(e)
print("dim",e.ndim)

[[[6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6]]]
dim 3


In [24]:
# create a 3D array

In [25]:
e = np.full((2,4,6),5)
print(e)
print("dim",e.ndim)

[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]]
dim 3


In [26]:
# create a 2x2 identity matrix

In [28]:
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
# create an array with random values

In [30]:
np.random.random((3,6))

array([[0.73400948, 0.60323035, 0.75868396, 0.44338425, 0.73617923,
        0.66939085],
       [0.81551616, 0.86766249, 0.73153827, 0.55190362, 0.92780052,
        0.21892777],
       [0.21262452, 0.47265425, 0.70928125, 0.81587965, 0.19049139,
        0.4134912 ]])

In [31]:
np.random.randint(3,14)

6

In [32]:
# to find shape of an array

In [33]:
arr = np.array([[1,2,3,4,5],
                [3,4,5,6,7],
                [8,9,1,3,9],
                [2,4,6,8,1]])
print(arr.shape)


(4, 5)


In [34]:
# to find no of elements in array

In [35]:
arr = np.array([[1,2,3,4,5],
                [3,4,5,6,7],
                [8,9,1,3,9],
                [2,4,6,8,1]])
print(arr.size)


20


In [36]:
# to find the length of array

In [42]:
import numpy as np
arr = np.array([[1,2,3,4,5],
                [3,4,5,6,7],
                [8,9,1,3,9],
                [2,4,6,8,1]])
len(arr)



4